//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ApostasBalasDataModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ApostasBalasDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ApostasBalasDBEntities object using the connection string found in the 'ApostasBalasDBEntities' section of the application configuration file.
        /// </summary>
        public ApostasBalasDBEntities() : base("name=ApostasBalasDBEntities", "ApostasBalasDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ApostasBalasDBEntities object.
        /// </summary>
        public ApostasBalasDBEntities(string connectionString) : base(connectionString, "ApostasBalasDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ApostasBalasDBEntities object.
        /// </summary>
        public ApostasBalasDBEntities(EntityConnection connection) : base(connection, "ApostasBalasDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Utilizador> Utilizador
        {
            get
            {
                if ((_Utilizador == null))
                {
                    _Utilizador = base.CreateObjectSet<Utilizador>("Utilizador");
                }
                return _Utilizador;
            }
        }
        private ObjectSet<Utilizador> _Utilizador;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Log> Log
        {
            get
            {
                if ((_Log == null))
                {
                    _Log = base.CreateObjectSet<Log>("Log");
                }
                return _Log;
            }
        }
        private ObjectSet<Log> _Log;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Utilizador EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUtilizador(Utilizador utilizador)
        {
            base.AddObject("Utilizador", utilizador);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Log EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLog(Log log)
        {
            base.AddObject("Log", log);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ApostasBalasDBModel", Name="Log")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Log : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Log object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="thread">Initial value of the Thread property.</param>
        /// <param name="level">Initial value of the Level property.</param>
        /// <param name="logger">Initial value of the Logger property.</param>
        /// <param name="message">Initial value of the Message property.</param>
        public static Log CreateLog(global::System.Int32 id, global::System.DateTime date, global::System.String thread, global::System.String level, global::System.String logger, global::System.String message)
        {
            Log log = new Log();
            log.Id = id;
            log.Date = date;
            log.Thread = thread;
            log.Level = level;
            log.Logger = logger;
            log.Message = message;
            return log;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                if (_Date != value)
                {
                    OnDateChanging(value);
                    ReportPropertyChanging("Date");
                    _Date = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Date");
                    OnDateChanged();
                }
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Thread
        {
            get
            {
                return _Thread;
            }
            set
            {
                if (_Thread != value)
                {
                    OnThreadChanging(value);
                    ReportPropertyChanging("Thread");
                    _Thread = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Thread");
                    OnThreadChanged();
                }
            }
        }
        private global::System.String _Thread;
        partial void OnThreadChanging(global::System.String value);
        partial void OnThreadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Level
        {
            get
            {
                return _Level;
            }
            set
            {
                if (_Level != value)
                {
                    OnLevelChanging(value);
                    ReportPropertyChanging("Level");
                    _Level = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Level");
                    OnLevelChanged();
                }
            }
        }
        private global::System.String _Level;
        partial void OnLevelChanging(global::System.String value);
        partial void OnLevelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Logger
        {
            get
            {
                return _Logger;
            }
            set
            {
                if (_Logger != value)
                {
                    OnLoggerChanging(value);
                    ReportPropertyChanging("Logger");
                    _Logger = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Logger");
                    OnLoggerChanged();
                }
            }
        }
        private global::System.String _Logger;
        partial void OnLoggerChanging(global::System.String value);
        partial void OnLoggerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                if (_Message != value)
                {
                    OnMessageChanging(value);
                    ReportPropertyChanging("Message");
                    _Message = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Message");
                    OnMessageChanged();
                }
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Exception
        {
            get
            {
                return _Exception;
            }
            set
            {
                OnExceptionChanging(value);
                ReportPropertyChanging("Exception");
                _Exception = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Exception");
                OnExceptionChanged();
            }
        }
        private global::System.String _Exception;
        partial void OnExceptionChanging(global::System.String value);
        partial void OnExceptionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ApostasBalasDBModel", Name="Utilizador")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Utilizador : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Utilizador object.
        /// </summary>
        /// <param name="idUtilizador">Initial value of the IdUtilizador property.</param>
        public static Utilizador CreateUtilizador(global::System.Int32 idUtilizador)
        {
            Utilizador utilizador = new Utilizador();
            utilizador.IdUtilizador = idUtilizador;
            return utilizador;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdUtilizador
        {
            get
            {
                return _IdUtilizador;
            }
            set
            {
                if (_IdUtilizador != value)
                {
                    OnIdUtilizadorChanging(value);
                    ReportPropertyChanging("IdUtilizador");
                    _IdUtilizador = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdUtilizador");
                    OnIdUtilizadorChanged();
                }
            }
        }
        private global::System.Int32 _IdUtilizador;
        partial void OnIdUtilizadorChanging(global::System.Int32 value);
        partial void OnIdUtilizadorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NomeUtilizador
        {
            get
            {
                return _NomeUtilizador;
            }
            set
            {
                OnNomeUtilizadorChanging(value);
                ReportPropertyChanging("NomeUtilizador");
                _NomeUtilizador = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NomeUtilizador");
                OnNomeUtilizadorChanged();
            }
        }
        private global::System.String _NomeUtilizador;
        partial void OnNomeUtilizadorChanging(global::System.String value);
        partial void OnNomeUtilizadorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Administrador
        {
            get
            {
                return _Administrador;
            }
            set
            {
                OnAdministradorChanging(value);
                ReportPropertyChanging("Administrador");
                _Administrador = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Administrador");
                OnAdministradorChanged();
            }
        }
        private Nullable<global::System.Boolean> _Administrador;
        partial void OnAdministradorChanging(Nullable<global::System.Boolean> value);
        partial void OnAdministradorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataCriacao
        {
            get
            {
                return _DataCriacao;
            }
            set
            {
                OnDataCriacaoChanging(value);
                ReportPropertyChanging("DataCriacao");
                _DataCriacao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataCriacao");
                OnDataCriacaoChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataCriacao;
        partial void OnDataCriacaoChanging(Nullable<global::System.DateTime> value);
        partial void OnDataCriacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataActualizacao
        {
            get
            {
                return _DataActualizacao;
            }
            set
            {
                OnDataActualizacaoChanging(value);
                ReportPropertyChanging("DataActualizacao");
                _DataActualizacao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataActualizacao");
                OnDataActualizacaoChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataActualizacao;
        partial void OnDataActualizacaoChanging(Nullable<global::System.DateTime> value);
        partial void OnDataActualizacaoChanged();

        #endregion

    
    }

    #endregion

    
}
